### ISSUE TITLE
Citation " characters in ffmpeg string

### ISSUE THREAD

**Issue by ma-blip** [RattleyCooper/ffmpeg_wrapper#1]
Hi!

Thanks for solving an anoying problem. I'm having some small issues when ffmpeg is using " citation characters. 

example -af "pan=4.0|c0=c0|c1=c1|c2=c2|c3=c3",aresample=async=1

Unable to find a suitable output format for ',aresample=async=1'
,aresample=async=1: Invalid argument

"DeckLink SDI (1)" is read by the wrapper as only Decklink it does not pass the whole string.

Any ideas how to inject  the " character correctly to ffmpeg?

Regards M

**Comment by Wykleph** [comment]
Is this an issue with the ffmpeg wrapper?  This might be better suited on the ffmpeg github page over at https://github.com/FFmpeg/FFmpeg

**Comment by RattleyCooper** [comment]
Can you post the entire command so I can do some testing?

**Comment by ma-blip** [comment]
You can use one of the examples with decklink and ffmpeg. You will need a compiled version with decklink support so might be hard to test without.

ffmpeg_wrap ffmpeg -channels 16 -format_code Hi50 -f decklink -i 'UltraStudio Mini Recorder' -c:a copy -c:v copy output.avi

'UltraStudio: No such device or address, FFmpeg only reads the whole UltraStudio Mini Recorder and starts record

You should be able to test with simple input filename containing spaces

ffmpeg -i "test file.mp4"
ok in ffmpeg

with wrapper test: No such file or directory, 

It read only the first word before the space in the filename.


/M

**Comment by ma-blip** [comment]
Seems like using  three """ will pass one " in the ffmpeg syntax. Im guessing this is somehow python related?

**Comment by RattleyCooper** [comment]
I apologize for the delay on working on this.  I'm in the Pacific NW and have been dodging fires the past couple days.  This may be python or nim related since they both use `"""` for multi-line strings.  I will do my best to check on this this evening.

**Comment by RattleyCooper** [comment]
Tracked down the issue.  It seems that nim is stripping the `"` character from the parameters automatically.  Running  `ffmpeg_wrap.exe ffmpeg.exe -i "test file.mp4" testfile.wmv` results in the following sequence of parameters:

`@["ffmpeg.exe", "-i", "test file.mp4", "testfile.wmv"]`

Notice the lack of encapsulating quotes around `test file.mp4`.

If there are no quotes around `test file.mp4`, but there is still a space in the parameter, it is safe to assume that the parameter had quotes (or else it would be added to the sequence as a different item), and we can reintroduce the quotes manually when there is a space character in one of the parameters.  I will get this fix implemented, tested and merged with the main branch.

**Comment by RattleyCooper** [comment]
@ma-blip the `ffmpeg_wrap.exe` release is updated with bug fix.  `ffmpeg_wrap.nim` is also updated so you can compile your own.  This issue should be fixed though.  I had limited time to test this fix though, so give it a shot and let me know!

**Comment by ma-blip** [comment]
Big thanks for taking your time to fix the problems.

Will try it out asap.

/M

**Comment by RattleyCooper** [comment]
Happy to help!  I'm going to close the issue for now.
